name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Black
      run: black --check src/ tests/

    - name: Run isort
      run: isort --check-only --profile black src/ tests/

    - name: Run Flake8
      run: flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503

    - name: Run Unit Tests
      run: pytest tests/test_data_preparation_unit.py -v --cov=src --cov-report=term-missing
