name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run Black
      run: black --check src/ setup.py

    - name: Run isort
      run: isort --check-only --profile black src/ setup.py

    - name: Run Flake8
      run: flake8 src/ setup.py --max-line-length=88 --extend-ignore=E203,W503

    # Future: Add test job when tests are implemented
    # test:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - uses: actions/checkout@v3
    #   - name: Set up Python
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.11'
    #   - name: Install dependencies
    #     run: |
    #       pip install -r requirements.txt
    #       pip install -r requirements-dev.txt
    #   - name: Run tests
    #     run: pytest tests/
